name: Install Rust tool
description: Install a Cargo tool via taiki-e/install-action

inputs:
  tool:
    description: Cargo binary to install
    required: true

runs:
  using: composite
  steps:
    - name: Install tool
      uses: taiki-e/install-action@704f92c11daa75bff5b4e01fcb083350c16c47b9 # v2.69.13
      with:
        tool: ${{ inputs.tool }}
